# Generated by Django 5.1.2 on 2024-10-22 20:53

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='technology',
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='skill_name_case_insensitive_unique', violation_error_message='Skill already exists (case insensitive match)')],
            },
        ),
        migrations.AddField(
            model_name='project',
            name='skill',
            field=models.ManyToManyField(help_text='Select a skill used for this project.', to='projects.skill'),
        ),
    ]
