# Generated by Django 5.1.2 on 2024-10-29 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_project_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_line_text', models.CharField(max_length=200)),
                ('main_text', models.TextField()),
            ],
        ),
    ]
