# Generated by Django 5.1.2 on 2024-10-30 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_aboutme'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimatedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('preview_image', models.ImageField(upload_to='images/previews/')),
                ('animated_gif', models.ImageField(upload_to='images/gifs/')),
            ],
        ),
    ]
