# Generated by Django 5.1.2 on 2024-10-30 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_animatedimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AnimatedImage',
        ),
        migrations.RemoveField(
            model_name='project',
            name='image',
        ),
        migrations.AddField(
            model_name='project',
            name='animated_gif',
            field=models.ImageField(null=True, upload_to='images/gifs/'),
        ),
        migrations.AddField(
            model_name='project',
            name='preview_image',
            field=models.ImageField(null=True, upload_to='images/previews/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
